name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          debug: true
          script: |
            echo "===== SSH SUCCESS ====="
            whoami
            hostname
            pwd
            ls -la