name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set +e

            echo "===== STEP 1 ====="
            whoami

            echo "===== STEP 2 ====="
            pwd

            echo "===== STEP 3 ====="
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"

            echo "===== STEP 4 ====="
            nvm use 16

            echo "===== STEP 5 ====="
            node -v

            echo "===== STEP 6 ====="
            npm -v

            echo "===== STEP 7 ====="
            cd ${{ secrets.PROJECT_PATH }}

            echo "===== STEP 8 ====="
            pwd

            echo "===== STEP 9 ====="
            git fetch origin

            echo "===== STEP 10 ====="
            git reset --hard origin/main

            echo "===== STEP 11 ====="
            cd backend

            echo "===== STEP 12 ====="
            npm install

            echo "===== STEP 13 ====="
            pm2 describe employee-backend

            echo "===== STEP 14 ====="
            pm2 restart employee-backend --update-env

            echo "Waiting 5 seconds..."
            sleep 5

            echo "===== STEP 15 ====="
            curl http://localhost:3000/api/health

            echo "===== FINISHED ====="