name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            set -e

            echo "===== STEP 1: Go to project ====="
            cd ${{ secrets.PROJECT_PATH }}

            echo "===== STEP 2: Pull latest code ====="
            git fetch origin
            git reset --hard origin/main

            echo "===== STEP 3: Load NVM manually ====="
            export NVM_DIR="/home/ec2-user/.nvm"
            source /home/ec2-user/.nvm/nvm.sh

            echo "===== STEP 4: Check NVM ====="
            command -v nvm

            echo "===== STEP 5: Use Node 16 ====="
            nvm use 16

            echo "===== STEP 6: Check Node ====="
            node -v
            npm -v

            echo "===== STEP 7: Frontend folder ====="
            cd frontend

            echo "===== STEP 8: Install packages ====="
            npm install

            echo "===== STEP 9: Build frontend ====="
            npm run build

            echo "===== STEP 10: Reload Nginx ====="
            sudo nginx -s reload

            echo "===== FRONTEND DEPLOYMENT FINISHED ====="